-- Rollback do diario da impressora: volta o CHECK de ops_events.event_type ao da 20261001100000.
-- Os eventos PRINTER_HMS/PRINTER_ERROR ja gravados saem antes (o CHECK antigo os recusaria).
DELETE FROM public.ops_events WHERE event_type IN ('PRINTER_HMS', 'PRINTER_ERROR');

ALTER TABLE public.ops_events DROP CONSTRAINT IF EXISTS ops_events_event_type_check;

ALTER TABLE public.ops_events ADD CONSTRAINT ops_events_event_type_check CHECK (event_type IN (
    'AGENT_STARTED', 'AGENT_STOPPED', 'AGENT_CRASH_RECOVERED',
    'MQTT_CONNECTED', 'MQTT_DISCONNECTED', 'MQTT_ERROR',
    'PRINTER_ONLINE', 'PRINTER_OFFLINE',
    'TELEMETRY_DEGRADED', 'TELEMETRY_RESTORED',
    'SESSION_LOST', 'SESSION_RECOVERED',
    'BAMBU_SYNC_FAILED', 'BAMBU_SYNC_RECOVERED',
    'PROFILE_SYNC_FAILED', 'PROFILE_SYNC_RECOVERED',
    'INBOX_ITEM_CREATED',
    'JOB_DETECTED', 'JOB_FINISHED', 'JOB_FAILED',
    'FTPS_FAILED',
    'FINALIZE_QUEUED', 'FINALIZE_RETRY', 'FINALIZE_COMPLETED', 'FINALIZE_FAILED',
    'SPOOL_AMBIGUOUS',
    'UNHANDLED_REJECTION', 'AGENT_ERROR',
    'WEB_ERROR', 'SUPPORT_REQUEST'
));

DELETE FROM supabase_migrations.schema_migrations WHERE version = '20261008100000';
